Replaced from and to argument with a month argument.
DannyvanderKraan/azure-carbon-cli pull request #15
Opened 2024-09-26 12:30 UTC by JvandeKraats

2024-09-26 12:32 UTC, JvandeKraats commented
Removed the validation code because month can't be null and the from and to checks are not needed anymore.

2024-09-26 12:57 UTC, DannyvanderKraan requested changes

2024-09-26 12:57 UTC, DannyvanderKraan commented on src/Properties/launchSettings.json
> +      "commandLineArgs": "--subscription 2193e77b-d7ae-498b-9a28-14abbd97dfe2 --month 2024-07-01"
if we strip out the from and to parameters, maybe its better to make the command line parameters  --year and --month and if you leave --year out it'll just be the current year? This way you don't have to deal with the day part.

2024-09-26 12:59 UTC, JvandeKraats commented on src/Properties/launchSettings.json
> +      "commandLineArgs": "--subscription 2193e77b-d7ae-498b-9a28-14abbd97dfe2 --month 2024-07-01"
That's a good point. I will implement this

2024-09-26 13:16 UTC, DannyvanderKraan approved these changes
LGTM

2024-09-27 08:14 UTC, merged

2024-09-27 08:34 UTC, DannyvanderKraan reviewed
LGTM